package boxes;

public enum EnumFrameSequenceId {

    SEQ_IDLE,
    SEQ_IDLE_NORTH,
    SEQ_IDLE_SOUTH,
    SEQ_IDLE_EAST,
    SEQ_IDLE_WEST,
    SEQ_IDLE_NORTHEAST,
    SEQ_IDLE_SOUTHEAST,
    SEQ_IDLE_SOUTHWEST,
    SEQ_IDLE_NORTHWEST,
    SEQ_WALK_NORTH,
    SEQ_WALK_SOUTH,
    SEQ_WALK_EAST,
    SEQ_WALK_WEST,
    SEQ_WALK_NORTHEAST,
    SEQ_WALK_SOUTHEAST,
    SEQ_WALK_SOUTHWEST,
    SEQ_WALK_NORTHWEST
}
