package boxes;

public enum EnumTextureId {

    TEX_BG_FERTILE,
    TEX_BG_NORMAL_FFFF,
    TEX_BG_NORMAL_FFFN,
    TEX_BG_NORMAL_FFNF,
    TEX_BG_NORMAL_FFNN,
    TEX_BG_NORMAL_FNFF,
    TEX_BG_NORMAL_FNFN,
    TEX_BG_NORMAL_FNNF,
    TEX_BG_NORMAL_FNNN,
    TEX_BG_NORMAL_NFFF,
    TEX_BG_NORMAL_NFFN,
    TEX_BG_NORMAL_NFNF,
    TEX_BG_NORMAL_NFNN,
    TEX_BG_NORMAL_NNFF,
    TEX_BG_NORMAL_NNFN,
    TEX_BG_NORMAL_NNNF,
    TEX_BG_NORMAL_NNNN,
    TEX_BG_DESERT,
    TEX_BG_WATER,
    TEX_BG_SNOW,
    TEX_BG_CREEPER
}
